version: '3.5'
services:
  app:
    container_name: reservo
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        APP_VERSION: ${APP_VERSION}
        APP_USERNAME: ${APP_USERNAME}
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - "/tmp/.m2:/root/.m2"
    ports:
      - "8082:8082"
    networks:
      - local-app-network
  mysql:
    container_name: mysql-instance
    build:
      context: docker/database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - local-app-network
    env_file:
      - .env
    healthcheck:
      test: "mysqladmin ping -u root -p$${DB_CREDENTIALS_PASSWORD}"
      start_period: 30s

networks:
  local-app-network:
    driver: "bridge"