name: Publish Docker image
on:
  push:
    branches:
      — '*'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        run: |
          echo "${{ env.APP_USERNAME }}"
        env:
          APP_USERNAME: ${{ env.APP_USERNAME }}
#         with:
#           APP_USERNAME: ${{ env.APP_USERNAME }}
#           file: ./docker/app/Dockerfile
#           push: true
#           tags: bustamista/reservo:latest
