name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  build_and_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASS
          
      - name: Build production image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/app/Dockerfile
          push: true
          tags: bustamista/reservo:latest
