name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  build_and_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      APP_USERNAME: "reservo"
      DOCKER_HUB_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_HUB_PASS: ${{ secrets.DOCKER_PASSWORD }}
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: echo $DOCKER_HUB_PASS | docker login docker.io -u $DOCKER_HUB_USER --password-stdin
      - run: |
          docker-compose build
          docker-compose push

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASS
          
#       - name: Start containers
#         run: docker-compose -f "docker-compose.yml" up -d --build
      
      - name: Push to Docker Hub
        with:
          push: true
          tags: bustamista/reservo:latest
